#!/usr/bin/dh-exec
src/verity_squash_root/default_config.ini => /etc/verity_squash_root/config.ini
src/verity_squash_root/default_config.ini => /usr/share/verity_squash_root/default.ini
usr/lib/dracut/modules.d/99verity-squash-root/* /usr/lib/dracut/modules.d/99verity-squash-root/
usr/lib/initcpio/install/verity-squash-root /usr/lib/initcpio/install/
usr/lib/systemd/system/verity-squash-root-notifiy.service /usr/lib/systemd/system/
usr/lib/verity-squash-root/* /usr/lib/verity-squash-root
usr/share/bash-completion/completions/verity-squash-root /usr/share/bash-completion/completions/
