name: Build Arch Linux package
on: [push]
jobs:
  build:
    permissions:
      actions: read
      checks: write
      contents: write
      issues: read
      packages: write
      pull-requests: read
      repository-projects: read
      statuses: read
    runs-on: ubuntu-latest
    name: Build Arch Linux package
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get install bubblewrap fakeroot fakechroot
      - run: sudo bash archlinux/install_pacman

      # Setup workspace
      - run: set -e
      - run: git submodule update --init --recursive
      - run: bash archlinux/setup_chroot
      - run: bash archlinux/build

      - name: Upload Release Asset
        uses: alexellis/upload-assets@0.4.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["verity-squash-root-*.pkg.tar.*"]'
